#!/bin/bash

. /etc/init.d/functions

while read line; do
	echo -n $line
	curl --silent $line > /tmp/qwe
	if egrep -q 'asshole|Oleg blocked your internet' /tmp/qwe; then
		echo_failure
	else
		echo_success
	fi
	echo
done < sanka.list
